name = "TeleQuEST"
uuid = "090ca348-5511-421f-9b0d-60bd3a641c9d"
authors = ["Jonathan Miller <jonathan.miller@fieldofnodes.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
