name = "TeleQuEST"
uuid = "090ca348-5511-421f-9b0d-60bd3a641c9d"
authors = ["Jonathan Miller <jonathan.miller@fieldofnodes.com> and contributors"]
version = "1.0.0-DEV"

[deps]
QuEST = "2f8c4c1a-2c62-410c-b829-98d6ce53c0c2"

[compat]
julia = "1.9"
QuEST = "1.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
